DROP DATABASE IF EXISTS BD_SHOPMI;
CREATE DATABASE BD_SHOPMI;
USE BD_SHOPMI;

-- ROL
CREATE TABLE ROL (
    CODROL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBREROL VARCHAR(100) NOT NULL,
    ESTROL TINYINT NOT NULL
);

-- CATEGORIA
CREATE TABLE CATEGORIA (
    CODCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    IMGCATEGORIA VARCHAR(50) NOT NULL,
    NOMCATEGORIA VARCHAR(50) NOT NULL,
    ESTCATEGORIA TINYINT NOT NULL
);

-- MARCA
CREATE TABLE MARCA (
    CODMARCA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBREMARCA VARCHAR(25) NOT NULL,
    ESTMARCA TINYINT NOT NULL
);

-- DISTRITO
CREATE TABLE DISTRITO (
    CODDISTRITO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBREDISTRITO VARCHAR(80) NOT NULL,
    CODPOSTAL VARCHAR(10) NOT NULL,
    ESTDISTRITO TINYINT NOT NULL
);

-- CLIENTE
CREATE TABLE CLIENTE (
    CODCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NUMEROCOMDOCUMENTO CHAR(8) NOT NULL,
    APELLIDOS VARCHAR(80) NOT NULL,
    NOMBRES VARCHAR(80) NOT NULL,
    CODDISTRITO INT NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    FECNAC DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    ESTCLIENTE TINYINT NOT NULL,
    FOREIGN KEY (CODDISTRITO) REFERENCES DISTRITO(CODDISTRITO)
);

-- EMPLEADO
CREATE TABLE EMPLEADO (
    CODEMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    NUMERODOCUMENTO CHAR(8) NOT NULL,
    APELLIDOS VARCHAR(80) NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    CODDISTRITO INT NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    FECNAC DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    ESTEMPLEADO TINYINT NOT NULL,
    FOREIGN KEY (CODDISTRITO) REFERENCES DISTRITO(CODDISTRITO)
);

-- USUARIO
CREATE TABLE USUARIO (
    CODUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    APEUSUARIO VARCHAR(80) NOT NULL,
    NOMUSUARIO VARCHAR(80) NOT NULL,
    CORUSUARIO VARCHAR(100) NOT NULL,
    CONUSUARIO VARCHAR(50) NOT NULL,
    FECCRE DATETIME DEFAULT NOW(),
    ESTUSUARIO TINYINT NOT NULL,
    CODEMPLEADO INT,
    CODROL INT,
    FOREIGN KEY (CODEMPLEADO) REFERENCES EMPLEADO(CODEMPLEADO),
    FOREIGN KEY (CODROL) REFERENCES ROL(CODROL)
);

-- PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    CODCATEGORIA INT NOT NULL,
    IMGPRODUCTO VARCHAR(50) NOT NULL,
    NOMPRODUCTO VARCHAR(70) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    PREUNI DECIMAL(10, 2) NOT NULL,
    CODMARCA INT NOT NULL,
    STOCK INT NOT NULL,
    ESTPRODUCTO TINYINT NOT NULL,
    FOREIGN KEY (CODCATEGORIA) REFERENCES CATEGORIA(CODCATEGORIA),
    FOREIGN KEY (CODMARCA) REFERENCES MARCA(CODMARCA)
);

-- PEDIDO
CREATE TABLE PEDIDO (
    CODPEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    CODCLIENTE INT NOT NULL,
    CODEMPLEADO INT NOT NULL,
    FECPED DATE NOT NULL,
    PRECIOTOTAL DECIMAL(18, 2),
    ACTPED VARCHAR(20) NOT NULL,
    ESTPED TINYINT NOT NULL,
    FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE),
    FOREIGN KEY (CODEMPLEADO) REFERENCES EMPLEADO(CODEMPLEADO)
);

-- DETALLEPEDIDO
CREATE TABLE DETALLEPEDIDO (
    CODPEDIDO INT NOT NULL,
    CODPRODUCTO INT NOT NULL,
    PREUNI DECIMAL(10, 2) NOT NULL,
    CANTIDAD INT NOT NULL,
    EST_PP TINYINT NOT NULL,
    PRIMARY KEY (CODPEDIDO, CODPRODUCTO),
    FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO(CODPEDIDO),
    FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO)
);